# SITE CONFIGURATION
title: | # your site title
  건축도시공간연구실 LAUS   
author: LAUS # You :P
description: > # Meta description of Homepage
  Lab for Architectural & Urban Space, 
  Department of Architecture & Architectural Engineering, 
  College of Engineering, Seoul National University
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://laus.snu.ac.kr" # the base hostname & protocol for your site, e.g. http://example.com

# # SEO PLUGIN
# social:
#   name: Your Name
#   links:
#     - https://twitter.com/BenBalter
#     - https://www.facebook.com/ben.balter
#     - https://www.linkedin.com/in/BenBalter
#     - https://plus.google.com/+BenBalter
#     - https://github.com/benbalter
#     - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: "https://laus.snu.ac.kr"}
  # - {name: 'About', link: '/about'}
  - {name: 'Members', link: '/members'}
  - {name: 'Teaching', link: '/teaching'}
  - {name: 'Research', link: '/research'}
  - {name: 'News', link: '/news'}
  - {name: 'Contact', link: '/contact'}

tagline: |-
  서울대학교 공과대학 건축학과  
  Lab for Architectural & Urban Space  
  Department of Architecture & Architectural Engineering, College of Engineering, Seoul National University

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

news_limit: 3

email: your-email@domain.com # email for form submission

# twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
# github_username:  janczizikow # replace with your_github_username or comment to remove link from footer
# instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

# disqus:
#   shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-tabs

collections:
  areas:
    output: true
    permalink: /research-area/:title/
  news:
    output: true

scholar:
  style: modern-language-association
